### ISSUE TITLE
Missing docs for header "Explorer-Interface-Name"

### ISSUE THREAD

**Issue by oleaha** [enonic/doc-explorer#16]
Hello!

There is no mention of the "Explorer-Interface-Name" header in the docs, it should possibly be added in this section? https://github.com/enonic/doc-explorer/blob/master/docs/keys.adoc#graphql-client

**Comment by sigdestad** [comment]
Hi Ole.

An example of using the GraphQL API was missing in the docs. This is now created here: https://developer.enonic.com/docs/explorer/stable/graphql

The main idea is that you pass the interface as a parameter. The header is currently an undocumented feature. I understand that this can be confusing given the current query tester.
