### ISSUE TITLE
Missing image in the doc

### ISSUE THREAD

**Issue by vot-enonic** [enonic/doc-explorer#6]
This image is missing from the Enonic Explorer entry in the Developer Portal:
https://developer.enonic.com/docs/explorer/stable/admin/images/collection-name.png

https://developer.enonic.com/docs/explorer/stable/admin/collections

**Comment by poi33** [comment]
@ComLock something you can change? Or Thomas?

**Comment by ComLock** [comment]
I copied the image into the docs/admin/images folder, and clicked [update] in enonic.com/admin contentstudio, but the image still isn't uploaded to Content Studio?

**Comment by sigdestad** [comment]
Hmm.. if these are images that go in the doc, they should be placed into this repo, not managed via Content Studio...

**Comment by ComLock** [comment]
Yes I did not manage the image via Content Studio, the [update] button is down
